module.exports = {
    CLIENT_CONNECTED:'CLIENT_CONNECTED',
    CLIENT_DISCONNECTED: 'PUBLISHER_DISCONNECTED',
    UPLOAD_STARTED: 'UPLOAD_STARTED',

    PHOTO_SENT:'PHOTO_SENT',
    PHOTO_RECEIVED:'PHOTO_RECEIVED',
}