module.exports = {
    PHOTO_SENT:'PHOTO_SENT',
    PHOTO_RECEIVED:'PHOTO_RECEIVED',
    PHOTO_UPLOADING: 'PHOTO_UPLOADING',
    CLIENT_CONNECTED: 'CLIENT_CONNECTED',
    CLIENT_DISCONNECTED: 'CLIENT_DISCONNECTED'
}