module.exports = {
    CLIENT_CONNECTED:'CLIENT_CONNECTED',
    CLIENT_DISCONNECTED: 'PUBLISHER_DISCONNECTED',
    UPLOAD_STARTED: 'UPLOAD_STARTED',
    TRANSFERRING_DATA: 'TRANSFERRING_DATA',

    TRANSFER_COMPLETED:'TRANSFER_COMPLETED',
    PHOTO_RECEIVED:'PHOTO_RECEIVED',
}